Repository kayac-chang/the-overlord-of-beggars, pull requests merged in 2024-10, with the labels that each got.

#4 Migrate to Poetry
  backend/Dockerfile
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  backend/requirements.txt
Labels: hacktoberfest-accepted

#8 feat: add compose file
  docker-compose.yml
Labels: hacktoberfest-accepted

#14 feat: add service layer for abstraction
  backend/app/main.py
  backend/app/services/__init__.py
  backend/app/services/open_point_store_search_service.py
  backend/app/services/store_search_reducer.py
  backend/app/services/store_search_service.py
Labels: enhancement

#12 feat: complete model of getting family-mart stores
  backend/app/data_sources/family_mart/__init__.py
  backend/app/data_sources/family_mart/get_store_detail.py
  backend/app/data_sources/family_mart/get_stores_by_geolocation.py
  backend/app/data_sources/family_mart/model.py
  backend/app/data_sources/family_mart/share.py
  backend/app/main.py
  backend/app/services/family_mart_store_search_service.py
  backend/app/services/store_search_reducer.py
Labels: enhancement, hacktoberfest-accepted

#16 feat(backend): get store by store id
  backend/app/data_sources/open_point/get_nearby_stores_by_geolocation.py
  backend/app/data_sources/open_point/get_store_by_store_id.py
  backend/app/main.py
  backend/app/services/family_mart_store_search_service.py
  backend/app/services/open_point_store_search_service.py
  backend/app/services/store_search_reducer.py
  backend/app/services/store_search_service.py
  backend/poetry.lock
  backend/pyproject.toml
  docs/data-sources/7-11_legacy.md
Labels: enhancement

#19 Translate full-width numbers to half-width in BeforeValidator
  backend/app/data_sources/family_mart/model.py
Labels: bug, hacktoberfest-accepted

#20 feat(frontend): brand and multi expands
  frontend/app/lib/utils.ts
  frontend/app/models/brand.ts
  frontend/app/models/store.ts
  frontend/app/routes/_landing._index/route.tsx
  frontend/app/routes/_landing._index/store_table.tsx
  frontend/app/services/get_near_expired_foods_by_store_id.ts
  frontend/app/services/search_stores.ts
Labels: enhancement

#24 feat(crawler): setup crawler and job
  .github/workflows/crawler-for-seven-eleven-stores.yml
  crawler/.gitignore
  crawler/requirements.txt
  crawler/seven-eleven-stores.py
Labels: enhancement

#25 feat(crawler): add notebook for seven eleven stores
  crawler/requirements.txt
  crawler/seven-eleven-stores.ipynb
  crawler/seven-eleven-stores.py
  docs/data-sources/7-11_legacy.md
Labels: enhancement

#26 feat: add seven eleven stores crawler script
  crawler/get_stores_by_city_and_town.py
  crawler/get_towns_by_city_id.py
  crawler/models.py
  crawler/seven-eleven-stores.py
  crawler/utils.py
Labels: enhancement

#27 feat(crawler): insert into database
  crawler/.env.example
  crawler/config.py
  crawler/requirements.txt
  crawler/seven-eleven-stores.py
Labels: enhancement
